[package]
name = "nativelink-scheduler"
version = "0.4.0"
edition = "2021"

[dependencies]
nativelink-error = { path = "../nativelink-error" }
nativelink-config = { path = "../nativelink-config" }
nativelink-util = { path = "../nativelink-util" }
nativelink-proto = { path = "../nativelink-proto" }
nativelink-metric = { path = "../nativelink-metric" }

# TODO(aaronmondal): This should not be a dependency. Move the corresponding
#                    files somewhere else.
nativelink-store = { path = "../nativelink-store" }
async-lock = { version = "3.4.0", features = ["std"], default-features = false }
async-trait = "0.1.81"
prost = { version = "0.13.1", default-features = false }
uuid = { version = "1.8.0", default-features = false, features = ["v4", "serde"] }
futures = { version = "0.3.30", default-features = false }
lru = { version = "0.12.3", default-features = false }
mock_instant = "0.5.0"
parking_lot = "0.12.2"
rand = { version = "0.8.5", default-features = false }
scopeguard = { version = "1.2.0", default-features = false }
tokio = { version = "1.38.0", features = ["fs", "rt-multi-thread", "signal", "io-util"], default-features = false }
tokio-stream = { version = "0.1.15", features = ["fs"], default-features = false }
tonic = { version = "0.12.0", features = ["transport", "tls"], default-features = false }
tracing = { version = "0.1.40", default-features = false }
serde = { version = "1.0.203", features = ["rc"] }
serde_json = "1.0.120"
static_assertions = "1.1.0"

[dev-dependencies]
nativelink-macro = { path = "../nativelink-macro" }
pretty_assertions = { version = "1.4.0", features = ["std"] }
