[package]
name = "nativelink-store"
version = "0.4.0"
edition = "2021"

[dependencies]
nativelink-error = { path = "../nativelink-error" }
nativelink-config = { path = "../nativelink-config" }
nativelink-util = { path = "../nativelink-util" }
nativelink-proto = { path = "../nativelink-proto" }
nativelink-metric = { path = "../nativelink-metric" }
async-lock = { version = "3.3.0", default-features = false }
async-trait = "0.1.80"
aws-config = { version = "1.5.4", default-features = false, features = [
  "rustls",
] }
aws-sdk-s3 = { version = "1.41.0", default-features = false }
aws-smithy-runtime = { version = "1.6.2" }
bincode = "1.3.3"
blake3 = { version = "1.5.2", default-features = false }
byteorder = { version = "1.5.0", default-features = false }
bytes = { version = "1.6.1", default-features = false }
filetime = "0.2.23"
fred = { version = "9.0.3", features = [
  "enable-rustls-ring",
  "metrics",
  "blocking-encoding",
  "custom-reconnect-errors",
  "sentinel-client",
  "sentinel-auth",
  "subscriber-client",
  "mocks",
] }
futures = { version = "0.3.30", default-features = false }
hex = { version = "0.4.3", default-features = false }
http-body = "1.0.1"
hyper = { version = "0.14.30" }
hyper-rustls = { version = "0.27.0", default-features = false, features = [
  "webpki-roots",
] }
lz4_flex = { version = "0.11.3", default-features = false }
parking_lot = "0.12.3"
prost = { version = "0.13.1", default-features = false }
rand = { version = "0.8.5", default-features = false }
serde = { version = "1.0.204", default-features = false }
tokio = "1.38.0"
tokio-stream = { version = "0.1.15", default-features = false }
tokio-util = { version = "0.7.11" }
tonic = { version = "0.12.0", default-features = false }
tracing = { version = "0.1.40", default-features = false }
uuid = { version = "1.10.0", default-features = false }

[dev-dependencies]
nativelink-macro = { path = "../nativelink-macro" }
pretty_assertions = { version = "1.4.0", features = ["std"] }
memory-stats = "1.2.0"
mock_instant = "0.3.2"
once_cell = { version = "1.19.0", default-features = false }
sha2 = { version = "0.10.8", default-features = false }
http = { version = "1.1.0", default-features = false }
aws-smithy-types = "1.2.0"
aws-smithy-runtime = { version = "1.6.2", features = [
  "test-util",
], default-features = false }
aws-sdk-s3 = { version = "1.41.0", features = [
  "rt-tokio",
], default-features = false }
aws-smithy-runtime-api = "1.7.1"
serial_test = { version = "3.1.1", features = [
  "async",
], default-features = false }
